package com.ppgames.demo.handler;

public enum MsgIds {
    Login(1),
    SaveDecros(3),
    GetShelfs(5),
    AddGoods(7),
    BatchAddGoods(9),
    ExpandShelf(11),
    UnlockShelfPos(13),
    HeartBeat(15),
    Sell(27),
    BuyEquip(19),
    ExpandEquipsCapacity(29),
    GetLogistics(21),
    AddLogistics(23),
    UnloadLogistics(25),
    UpgradeLogistics(31),
    AccelerateLogistics(33),
    RemoveGoods(35),
    CreateRole(37),
    FaceCombine(39),
    FaceLevelUp(41),
    FaceChange(43),
    ChangePlayerEquips(45),
    UpgradeDressRoom(47),
    UnlockWindow(49),
    ChangeWindowEquips(51),
    GardenLowBuy(53),
    GardenHighBuy(55),
    GardenHighBuy10(57),
    GardenExchange(59),
    GetGarden(61),
    SowSeed(63),
    OverSeed(65),
    UnlockFactoryEquip(67),
    GetFactorys(69),
    AddFactory(71),
    UpgradeFactory(73),
    AccelerateFactory(75),
    UnloadFactory(77),
    FactoryMake(79),
    CashRegisterLevelUp(81),
    Employ(83),
    OverEmploy(85),
    ShopBuy(87),
    Rename(89),
    ChangePlayerHead(91),
    CheckIn(93),
    OpenCheckInChest(95),
    ExpandShop(97),
    MailList(99),
    MailUpdate(101),
    MailAttach(103),
    MailDelAll(105),
    MailAttachAll(107),
    RequestAddFriend(109),
    AgreeAddFriend(111),
    RefuseAddFriend(113),
    GetFriends(115),
    GetFriendRequests(117),
    GiveFriendFlower(119),
    DeleteFriend(121),
    GetCheckInStates(123),
    RecommendFriends(125),
    SearchFriend(127),
    VisitFriendRoom(129),
    PvpRefreshEnemys(131),
    PvpBattle(135),
    PvpBuyBattleNum(137),
    CrystalBuy(139),
    GetRanks(141),
    GetMainLineQuest(151),
    GetActiveValueQuest(153),
    TakeActiveValueReward(155),
    ActiveValueRaffle(157),
    TakeMainLineReward(159),
    GetCustomerQuests(161),
    TakeCustomerQuestRewards(163),
    GetNpcQuest(165),
    TakeNpcQuestRewards(167),
    SendChatMsg(169),
    ClearnRubbishs(171),
    StampExchange(173),
    GetSaleQuest(175),
    BeginSaleQuest(177),
    TakeSaleQuestRewards(179),
    BindingWXSuccess(181),
    BuyFund(183),
    GetActivityGroup(185),
    GetActivityQuest(187),
    GetActivityQuestReward(189),
    AccelerateFlower(191),
    GetFlowerRecode(193),
    GetPlayerInfo(195);

    int val;

    MsgIds(int val) {
        this.val = val;
    }

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }
}
